spring:
  application:
    name: ecommerce.api
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
  flyway:
    enabled: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 #5mins
    refreshTokenExpiration: 604800
  config:
    import: optional:file:.env[.properties]


