spring:
  application:
    name: ecommerce.api
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
  flyway:
    enabled: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 #15mins
    refreshTokenExpiration: 604800
  config:
    import: optional:file:.env[.properties]
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  data:
    redis:
      host: localhost
      port: 6379
app:
  otp:
    secret: ${OTP_SECRET}
    ttl-minutes: 10
    max-attempts: 5
    resend-cooldown-seconds: 60
    hourly-limit: 5




